import { StyleSheet } from 'react-native';
import { BOARD_SIZE, CELL_SIZE } from '../constants';

export const styles = StyleSheet.create({
  royaleContainer: { flex:1, backgroundColor:'#0a0f1d', alignItems:'center', justifyContent:'space-between', paddingVertical:14, paddingHorizontal:16 },
  dashboardContainer: { flex:1, backgroundColor:'#0a0f1d', width:'100%', height:'100%' },
  lobbyBgImage: { width:'100%', height:'100%', position:'absolute', top:0, left:0, right:0, bottom:0 },
  fulfilledTopActionCenterBar: { width:'100%', alignItems:'center', paddingTop:22, zIndex:30 },
  topActionCenterInnerRow: { width:'90%', flexDirection:'row', justifyContent:'space-between', backgroundColor:'rgba(15,23,42,0.88)', borderWidth:1.5, borderColor:'#facc15', borderRadius:16, paddingVertical:8, paddingHorizontal:10, elevation:8 },
  megaFulfilledButton: { flex:1, alignItems:'center', justifyContent:'center', backgroundColor:'#1e293b', marginHorizontal:4, paddingVertical:6, borderRadius:10, borderWidth:1, borderColor:'#334155', position:'relative' },
  megaFulfilledEmoji: { fontSize:18, marginBottom:1 },
  megaFulfilledText: { color:'#ffffff', fontSize:10, fontWeight:'900', textAlign:'center' },
  friendNotificationBadge: { position:'absolute', top:-4, right:2, backgroundColor:'#ef4444', minWidth:16, height:16, borderRadius:8, justifyContent:'center', alignItems:'center', borderWidth:1.5, borderColor:'#ffffff', paddingHorizontal:2, elevation:6 },
  friendNotificationBadgeText: { color:'#ffffff', fontSize:9, fontWeight:'900' },
  tabRedDotIndicator: { width:7, height:7, borderRadius:3.5, backgroundColor:'#ef4444', marginLeft:4 },
  centerBannerProfileWrapPerfect: { width:'100%', alignItems:'center', marginTop:12, zIndex:15 },
  centerCrownPosition: { marginBottom:-13, zIndex:5, alignItems:'center' },
  centerBannerContainerPerfect: { width:'78%', backgroundColor:'rgba(20,30,50,0.95)', borderWidth:2, borderColor:'#facc15', borderRadius:16, paddingVertical:6, paddingHorizontal:12, alignItems:'center', shadowColor:'#facc15', shadowOpacity:0.5, shadowRadius:8, elevation:8 },
  centerBannerUsername: { color:'#ffffff', fontSize:15, fontWeight:'900', letterSpacing:0.5, textAlign:'center', maxWidth:'100%' },
  centerBannerCoinsRow: { flexDirection:'row', alignItems:'center', marginTop:2, justifyContent:'center' },
  centerBannerCoinsText: { color:'#facc15', fontSize:13, fontWeight:'800' },
  viewProfileSubHint: { color:'#38bdf8', fontSize:9, fontWeight:'bold', marginTop:2, letterSpacing:0.5 },
  podiumTouchLayer: { position:'absolute', top:'38%', left:'4%', right:'4%', height:360, flexDirection:'row', flexWrap:'wrap', justifyContent:'space-between', alignContent:'space-between', zIndex:20 },
  podiumTouchSpot: { width:'47%', height:165, borderRadius:24 },
  squadTopHeaderRow: { flexDirection:'row', justifyContent:'space-between', alignItems:'center', width:'100%', borderBottomWidth:1, borderBottomColor:'#1e293b', paddingBottom:8 },
  squadMainTitle: { color:'#facc15', fontSize:18, fontWeight:'900', letterSpacing:1 },
  squadSubTitle: { color:'#94a3b8', fontSize:11, fontWeight:'600', marginTop:1 },
  squadCloseCrossBtn: { padding:6, backgroundColor:'#1e293b', borderRadius:14, borderWidth:1, borderColor:'#334155' },
  squadCloseCrossText: { color:'#ffffff', fontSize:13, fontWeight:'bold' },
  myIdPlankBar: { flexDirection:'row', justifyContent:'space-between', alignItems:'center', width:'100%', backgroundColor:'#0a192f', paddingHorizontal:12, paddingVertical:8, borderRadius:10, borderWidth:1, borderColor:'#38bdf8', marginTop:10 },
  myIdPlankText: { color:'#ffffff', fontSize:13, fontWeight:'700' },
  copyIdPillBtn: { backgroundColor:'#0284c7', paddingHorizontal:10, paddingVertical:4, borderRadius:6 },
  copyIdPillText: { color:'#ffffff', fontWeight:'bold', fontSize:11 },
  topSquadSearchRow: { flexDirection:'row', width:'100%', marginTop:8 },
  topSquadSearchInput: { flex:1, backgroundColor:'#0a0f1d', borderWidth:1, borderColor:'#334155', borderRadius:10, color:'#ffffff', paddingHorizontal:12, paddingVertical:8, fontSize:12 },
  topSquadSearchBtn: { backgroundColor:'#eab308', borderRadius:10, paddingHorizontal:14, justifyContent:'center', alignItems:'center', marginLeft:6 },
  topSquadSearchBtnText: { color:'#000000', fontWeight:'900', fontSize:12 },
  searchedPlayerCardBox: { flexDirection:'row', justifyContent:'space-between', alignItems:'center', width:'100%', backgroundColor:'#0a0f1d', padding:10, borderRadius:12, marginTop:8, borderWidth:1.5, borderColor:'#facc15' },
  addFriendActionBtn: { backgroundColor:'#10b981', paddingHorizontal:12, paddingVertical:6, borderRadius:8 },
  addFriendActionText: { color:'#ffffff', fontWeight:'900', fontSize:11 },
  cleanTabsRow: { flexDirection:'row', justifyContent:'space-between', width:'100%', marginTop:10, backgroundColor:'#0a0f1d', padding:3, borderRadius:10, borderWidth:1, borderColor:'#334155' },
  cleanTabPill: { flex:1, paddingVertical:7, alignItems:'center', borderRadius:8 },
  cleanTabPillActive: { backgroundColor:'#0284c7' },
  cleanTabText: { color:'#94a3b8', fontSize:10, fontWeight:'700' },
  cleanTabTextActive: { color:'#ffffff', fontWeight:'900' },
  squadTabScrollFeed: { maxHeight:220, width:'100%', marginTop:8 },
  squadEmptyStateText: { color:'#94a3b8', textAlign:'center', fontSize:12, marginTop:24, paddingHorizontal:16 },
  friendItemCardWrap: { flexDirection:'row', justifyContent:'space-between', alignItems:'center', backgroundColor:'#0a0f1d', padding:10, borderRadius:12, marginVertical:4, borderWidth:1, borderColor:'#1e293b' },
  avatarWithRingBox: { position:'relative', width:34, height:34, borderRadius:17, backgroundColor:'#1e293b', justifyContent:'center', alignItems:'center', borderWidth:1.5, borderColor:'#38bdf8' },
  onlineIndicatorDot: { position:'absolute', bottom:-2, right:-2, width:9, height:9, borderRadius:4.5, borderWidth:1.5, borderColor:'#0a0f1d' },
  friendCardNameText: { color:'#ffffff', fontWeight:'bold', fontSize:13 },
  friendCardSubText: { color:'#94a3b8', fontSize:10, marginTop:1 },
  inviteFriendActionBtn: { backgroundColor:'#10b981', paddingHorizontal:12, paddingVertical:6, borderRadius:8 },
  inviteFriendActionText: { color:'#ffffff', fontWeight:'bold', fontSize:11 },
  profileModalHeader: { alignItems:'center', marginBottom:6 },
  profileStatsTitle: { color:'#facc15', fontSize:20, fontWeight:'900', letterSpacing:1 },
  profileStatsSubId: { color:'#38bdf8', fontSize:12, fontWeight:'bold', marginTop:2 },
  statsRowGrid: { flexDirection:'row', justifyContent:'space-between', width:'100%', marginVertical:12 },
  statBoxCard: { width:'23%', backgroundColor:'#0a0f1d', borderRadius:12, paddingVertical:10, alignItems:'center', borderWidth:1.5, borderColor:'#334155' },
  statBoxNumber: { color:'#ffffff', fontSize:18, fontWeight:'900' },
  statBoxLabel: { color:'#94a3b8', fontSize:10, fontWeight:'700', marginTop:2 },
  prizePoolPreviewBox: { backgroundColor:'#1e293b', borderRadius:12, padding:10, alignItems:'center', borderWidth:1.5, borderColor:'#facc15', marginTop:8 },
  prizePoolPreviewLabel: { color:'#94a3b8', fontSize:11, fontWeight:'bold' },
  prizePoolPreviewAmount: { color:'#facc15', fontSize:18, fontWeight:'900', marginTop:2 },
  prizePoolBadgeLobby: { backgroundColor:'#78350f', paddingHorizontal:14, paddingVertical:6, borderRadius:10, borderWidth:1.5, borderColor:'#facc15', marginVertical:4 },
  prizePoolBadgeLobbyText: { color:'#facc15', fontWeight:'900', fontSize:13 },
  inGamePoolBox: { backgroundColor:'#78350f', paddingHorizontal:10, paddingVertical:5, borderRadius:8, borderWidth:1, borderColor:'#facc15' },
  inGamePoolText: { color:'#facc15', fontWeight:'bold', fontSize:12 },
  settingsSectionCard: { width:'100%', backgroundColor:'#0a0f1d', borderRadius:14, padding:12, borderWidth:1, borderColor:'#334155', marginVertical:6, alignItems:'center' },
  settingsSectionTitle: { color:'#38bdf8', fontSize:12, fontWeight:'900', letterSpacing:1, marginBottom:8, alignSelf:'flex-start' },
  profileBigAvatarWrap: { width:75, height:75, borderRadius:38, backgroundColor:'#1e293b', justifyContent:'center', alignItems:'center', borderWidth:2.5, borderColor:'#facc15', marginVertical:6, position:'relative' },
  editAvatarBadge: { position:'absolute', bottom:-4, backgroundColor:'#0284c7', paddingHorizontal:6, paddingVertical:1, borderRadius:6, borderWidth:1, borderColor:'#ffffff' },
  infoLineRow: { flexDirection:'row', justifyContent:'space-between', width:'100%', paddingVertical:5, borderBottomWidth:0.5, borderBottomColor:'#1e293b' },
  infoFieldLabel: { color:'#94a3b8', fontSize:12, fontWeight:'bold' },
  infoFieldValue: { color:'#ffffff', fontSize:12, fontWeight:'bold', maxWidth:170 },
  avatarPickerTriggerBtn: { marginTop:10, backgroundColor:'#1e293b', paddingVertical:8, paddingHorizontal:12, borderRadius:10, borderWidth:1, borderColor:'#facc15', width:'100%', alignItems:'center' },
  avatarPickerTriggerText: { color:'#facc15', fontWeight:'bold', fontSize:12 },
  soundToggleRow: { flexDirection:'row', justifyContent:'space-between', alignItems:'center', width:'100%', paddingVertical:4 },
  soundLabelText: { color:'#ffffff', fontSize:13, fontWeight:'bold' },
  aboutGoldTitle: { color:'#facc15', fontSize:16, fontWeight:'900', marginTop:2 },
  aboutVersionText: { color:'#94a3b8', fontSize:11, marginBottom:6 },
  aboutCreatorText: { color:'#ffffff', fontSize:12, fontWeight:'700' },
  aboutContactText: { color:'#38bdf8', fontSize:12, fontWeight:'600', marginTop:2 },
  logoutSettingsBtn: { width:'100%', backgroundColor:'#ef4444', borderRadius:12, paddingVertical:12, alignItems:'center', marginTop:10, borderWidth:1, borderColor:'#fca5a5' },
  logoutSettingsText: { color:'#ffffff', fontWeight:'900', fontSize:13, letterSpacing:0.5 },
  podiumTitleHeader: { color:'#facc15', fontSize:20, fontWeight:'900', textAlign:'center', letterSpacing:1 },
  podiumSubHeader: { color:'#94a3b8', fontSize:12, fontWeight:'700', textAlign:'center', marginBottom:14 },
  leaderboardListWrap: { width:'100%', maxHeight:240, marginVertical:6 },
  leaderboardRowItem: {
    flexDirection:'row',
    alignItems:'center',
    justifyContent:'space-between',
    backgroundColor:'#0a0f1d',
    borderRadius:12,
    paddingVertical:10,
    paddingHorizontal:12,
    marginVertical:4,
    borderWidth:1.5,
    borderColor:'#334155'
  },
  leaderboardHostRow: { borderColor:'#facc15', backgroundColor:'#1e293b' },
  rankBadgeText: {
    fontSize: 14,
    fontWeight: '900',
    color: '#ffffff',
    width: 60
  },
  rankPlayerName: {
    fontSize: 13,
    fontWeight: 'bold',
    flex: 1,
    marginLeft: 8,
    color: '#ffffff'
  },
  rankColorSub: { fontSize:10, color:'#94a3b8', fontWeight:'600' },
  rankCoinBox: { backgroundColor:'#78350f', paddingHorizontal:8, paddingVertical:4, borderRadius:8, borderWidth:1, borderColor:'#facc15' },
  rankCoinText: { color:'#facc15', fontWeight:'900', fontSize:12 },
  baseRankBanner: { position:'absolute', top:4, backgroundColor:'#78350f', paddingHorizontal:6, paddingVertical:2, borderRadius:6, borderWidth:1, borderColor:'#facc15', zIndex:10 },
  baseRankBannerText: { color:'#fef08a', fontSize:10, fontWeight:'900' },
  avatarSelectionCard: { width:'95%', backgroundColor:'#022144', borderRadius:24, padding:14, borderWidth:3, borderColor:'#facc15', alignItems:'center', elevation:12 },
  avatarPreviewTopBox: { flexDirection:'row', alignItems:'center', justifyContent:'center', width:'100%', marginBottom:12 },
  avatarPreviewCircle: { width:56, height:56, borderRadius:28, backgroundColor:'#1e3a8a', borderWidth:2, borderColor:'#38bdf8', justifyContent:'center', alignItems:'center', marginRight:10 },
  avatarPreviewNamePlank: { backgroundColor:'#ffffff', borderWidth:2, borderColor:'#94a3b8', borderStyle:'dashed', borderRadius:10, paddingHorizontal:20, paddingVertical:8, minWidth:150, alignItems:'center' },
  avatarPreviewNameText: { color:'#000000', fontWeight:'900', fontSize:15 },
  avatarCategoryRow: { flexDirection:'row', justifyContent:'space-between', width:'100%', marginBottom:10 },
  avatarTabBtn: { flex:1, backgroundColor:'#0f172a', paddingVertical:8, alignItems:'center', borderRadius:10, marginHorizontal:3, borderWidth:1, borderColor:'#334155' },
  avatarTabActiveMale: { backgroundColor:'#0284c7', borderColor:'#38bdf8' },
  avatarTabActiveFemale: { backgroundColor:'#db2777', borderColor:'#f472b6' },
  avatarTabActiveRoyale: { backgroundColor:'#ca8a04', borderColor:'#facc15' },
  avatarTabText: { color:'#ffffff', fontWeight:'bold', fontSize:12 },
  selectPicHeading: { color:'#facc15', fontSize:16, fontWeight:'900', letterSpacing:1, marginVertical:6 },
  avatarGridContainer: { flexDirection:'row', flexWrap:'wrap', justifyContent:'space-between', width:'100%' },
  avatarGridTile: { width:'31%', height:85, backgroundColor:'#0a192f', borderRadius:12, borderWidth:1.5, borderColor:'#1e3a8a', justifyContent:'center', alignItems:'center', marginVertical:4 },
  avatarGridTileSelected: { borderColor:'#facc15', backgroundColor:'#1e3a8a', borderWidth:2.5, elevation:6 },
  avatarTileLabel: { color:'#94a3b8', fontSize:10, fontWeight:'bold', marginTop:2 },
  matchmakingContainer: { flex:1, backgroundColor:'#881337', alignItems:'center', justifyContent:'space-between', paddingVertical:18, paddingHorizontal:16 },
  matchLobbyHeader: { alignItems:'center', marginTop:4 },
  matchLobbyTitle: { color:'#facc15', fontSize:22, fontWeight:'900', letterSpacing:1.5 },
  matchFormatSub: { color:'#ffffff', fontSize:12, fontWeight:'800', marginTop:2, letterSpacing:1 },
  matchCodeCard: { flexDirection:'row', alignItems:'center', backgroundColor:'#450a0a', paddingHorizontal:14, paddingVertical:8, borderRadius:14, borderWidth:2, borderColor:'#f87171', marginTop:8 },
  matchCodeLabel: { color:'#ffffff', fontWeight:'bold', fontSize:15 },
  codePillBox: { backgroundColor:'#1e3a8a', paddingHorizontal:12, paddingVertical:4, borderRadius:8, borderWidth:1, borderColor:'#38bdf8' },
  codePillText: { color:'#facc15', fontWeight:'900', fontSize:18, letterSpacing:2 },
  shareCodeBtn: { backgroundColor:'#10b981', paddingHorizontal:12, paddingVertical:6, borderRadius:8, marginLeft:10 },
  shareCodeText: { color:'#ffffff', fontWeight:'bold', fontSize:12 },
  soloMatchLobbyWrap: { width:'100%', alignItems:'center', marginVertical:4 },
  hostProfileBox: { alignItems:'center', marginTop:6 },
  hostAvatarSquare: { width:84, height:84, borderRadius:18, backgroundColor:'#7f1d1d', borderWidth:2.5, borderColor:'#facc15', justifyContent:'center', alignItems:'center', elevation:8 },
  hostNameText: { color:'#ffffff', fontWeight:'900', fontSize:15, marginTop:4 },
  hostBadgeText: { color:'#38bdf8', fontWeight:'800', fontSize:10, marginTop:1 },
  vsGlowBanner: { marginVertical:6 },
  vsGlowText: { color:'#facc15', fontSize:20, fontWeight:'900', letterSpacing:2 },
  opponentSlotsRow: { flexDirection:'row', justifyContent:'center', width:'100%', marginVertical:6 },
  slotInviteBox: { width:88, height:95, borderRadius:16, backgroundColor:'#7f1d1d', borderWidth:2, borderColor:'#fca5a5', borderStyle:'dashed', justifyContent:'center', alignItems:'center', marginHorizontal:6, elevation:4 },
  plusAvatarIcon: { fontSize:28, color:'#fecaca' },
  inviteSlotLabel: { color:'#fecaca', fontSize:9, fontWeight:'bold', marginTop:4, textAlign:'center' },
  joinedSlotName: { color:'#ffffff', fontSize:11, fontWeight:'bold', maxWidth:75, textAlign:'center', marginTop:2 },
  joinedSlotTag: { fontSize:9, fontWeight:'900', marginTop:1 },
  teamMatchLobbyWrap: { width:'100%', marginVertical:2 },
  teamLobbyBoxA: { backgroundColor:'rgba(2,132,199,0.25)', borderWidth:1.5, borderColor:'#38bdf8', borderRadius:16, padding:8, alignItems:'center' },
  teamLobbyBoxB: { backgroundColor:'rgba(225,29,72,0.25)', borderWidth:1.5, borderColor:'#fb7185', borderRadius:16, padding:8, alignItems:'center' },
  teamLobbyTitleA: { color:'#38bdf8', fontWeight:'900', fontSize:12, marginBottom:6, letterSpacing:0.5 },
  teamLobbyTitleB: { color:'#fb7185', fontWeight:'900', fontSize:12, marginBottom:6, letterSpacing:0.5 },
  teamSlotsRow: { flexDirection:'row', justifyContent:'space-around', width:'100%' },
  playerSquareActive: { width:100, height:86, borderRadius:14, backgroundColor:'#1e3a8a', borderWidth:1.5, borderColor:'#38bdf8', justifyContent:'center', alignItems:'center' },
  slotBoxFilledBlue: { backgroundColor:'#1e3a8a', borderColor:'#38bdf8', borderStyle:'solid' },
  slotBoxFilledGreen: { backgroundColor:'#14532d', borderColor:'#4ade80', borderStyle:'solid' },
  slotBoxFilledRed: { backgroundColor:'#881337', borderColor:'#fb7185', borderStyle:'solid' },
  slotBoxFilledYellow: { backgroundColor:'#713f12', borderColor:'#facc15', borderStyle:'solid' },
  slotPlayerNameText: { color:'#ffffff', fontWeight:'bold', fontSize:11, maxWidth:85, textAlign:'center', marginTop:2 },
  slotRoleTagBlue: { color:'#38bdf8', fontSize:8, fontWeight:'900', marginTop:1 },
  slotRoleTagGreen: { color:'#4ade80', fontSize:8, fontWeight:'900', marginTop:1 },
  slotRoleTagRed: { color:'#fb7185', fontSize:8, fontWeight:'900', marginTop:1 },
  slotRoleTagYellow: { color:'#facc15', fontSize:8, fontWeight:'900', marginTop:1 },
  matchBottomActions: { width:'100%', alignItems:'center', marginBottom:6 },
  startMatchGoldBtn: { width:'90%', backgroundColor:'#eab308', borderWidth:1.5, borderColor:'#fef08a', borderRadius:14, paddingVertical:13, alignItems:'center', elevation:6 },
  startMatchGoldText: { color:'#000000', fontSize:15, fontWeight:'900', letterSpacing:1 },
  cancelMatchBtn: { marginTop:8, paddingVertical:4 },
  cancelMatchText: { color:'#fca5a5', fontWeight:'bold', fontSize:13 },
  inviteDetailsBox: { backgroundColor:'#0a0f1d', borderRadius:12, padding:12, marginVertical:12, alignItems:'center', borderWidth:1, borderColor:'#334155' },
  inviteRoomTag: { color:'#38bdf8', fontSize:14, fontWeight:'bold', marginTop:4 },
  inviteModeTag: { color:'#4ade80', fontSize:12, fontWeight:'800', marginTop:2 },
  brandHero: { alignItems:'center', marginTop:4 },
  crownEmoji: { fontSize:36, marginBottom:2 },
  brandGoldTitle: { fontSize:24, fontWeight:'900', color:'#facc15', letterSpacing:1.5, textAlign:'center' },
  goldPillBadge: { backgroundColor:'#78350f', borderColor:'#facc15', borderWidth:1, borderRadius:20, paddingHorizontal:12, paddingVertical:3, marginTop:4 },
  goldPillText: { color:'#fef08a', fontSize:10, fontWeight:'800', letterSpacing:1 },
  glassCard: { width:'100%', backgroundColor:'#131c31', borderRadius:20, padding:16, borderWidth:1.5, borderColor:'#1e293b', shadowColor:'#000', shadowOpacity:0.5, shadowRadius:15, elevation:8 },
  cardHeading: { fontSize:18, fontWeight:'bold', color:'#ffffff', textAlign:'center', marginBottom:14, letterSpacing:1 },
  inputLabel: { color:'#94a3b8', fontSize:12, fontWeight:'700', marginBottom:6, letterSpacing:0.5 },
  gameTextInput: { backgroundColor:'#0a0f1d', borderWidth:1.5, borderColor:'#334155', borderRadius:12, color:'#ffffff', paddingHorizontal:16, paddingVertical:12, fontSize:15, fontWeight:'600' },
  gold3DButton: { backgroundColor:'#eab308', borderColor:'#fef08a', borderWidth:1.5, borderRadius:14, paddingVertical:14, alignItems:'center', shadowColor:'#facc15', shadowOpacity:0.4, shadowRadius:8, elevation:6 },
  gold3DButtonText: { color:'#000000', fontSize:14, fontWeight:'900', letterSpacing:1 },
  forgotHeaderBox: { alignItems:'center', marginBottom:8 },
  forgotTitle: { color:'#facc15', fontSize:16, fontWeight:'bold' },
  forgotSubtitle: { color:'#94a3b8', fontSize:11, textAlign:'center', marginTop:2 },
  forgotLinkContainer: { alignSelf:'flex-end', marginTop:8, paddingVertical:4 },
  forgotLinkText: { color:'#38bdf8', fontSize:12, fontWeight:'bold' },
  orDivider: { flexDirection:'row', alignItems:'center', marginVertical:12 },
  dividerLine: { flex:1, height:1, backgroundColor:'#334155', marginVertical:6 },
  orText: { color:'#64748b', paddingHorizontal:12, fontSize:11, fontWeight:'bold' },
  darkSecondaryButton: { backgroundColor:'#1e293b', borderRadius:14, paddingVertical:12, alignItems:'center', borderWidth:1, borderColor:'#475569' },
  darkSecondaryButtonText: { color:'#cbd5e1', fontSize:13, fontWeight:'700' },
  tabToggleRow: { flexDirection:'row', backgroundColor:'#0a0f1d', borderRadius:12, padding:4, borderWidth:1, borderColor:'#334155' },
  tabToggleBtn: { flex:1, paddingVertical:10, alignItems:'center', borderRadius:8 },
  tabToggleActive: { backgroundColor:'#0284c7' },
  tabToggleText: { color:'#94a3b8', fontSize:11, fontWeight:'bold' },
  tabToggleTextActive: { color:'#ffffff' },
  playerCountRow: { flexDirection:'row', justifyContent:'space-between', marginVertical:8 },
  countPill: { flex:1, backgroundColor:'#0a0f1d', borderWidth:1.5, borderColor:'#334155', borderRadius:10, paddingVertical:10, alignItems:'center', marginHorizontal:4 },
  countPillActive: { borderColor:'#10b981', backgroundColor:'#064e3b' },
  countPillText: { color:'#94a3b8', fontWeight:'bold', fontSize:12 },
  countPillTextActive: { color:'#ffffff' },
  teamContainerBoxA: { backgroundColor:'rgba(2,132,199,0.12)', borderWidth:1.5, borderColor:'#0284c7', borderRadius:14, padding:10, marginBottom:4 },
  teamContainerBoxB: { backgroundColor:'rgba(225,29,72,0.12)', borderWidth:1.5, borderColor:'#e11d48', borderRadius:14, padding:10, marginTop:4 },
  teamHeaderRow: { flexDirection:'row', justifyContent:'space-between', alignItems:'center', marginBottom:8, paddingHorizontal:4 },
  teamHeaderTitleA: { color:'#38bdf8', fontWeight:'900', fontSize:13, letterSpacing:0.5 },
  teamHeaderTitleB: { color:'#fb7185', fontWeight:'900', fontSize:13, letterSpacing:0.5 },
  teamBadgeA: { backgroundColor:'#0369a1', paddingHorizontal:8, paddingVertical:2, borderRadius:6 },
  teamBadgeB: { backgroundColor:'#9f1239', paddingHorizontal:8, paddingVertical:2, borderRadius:6 },
  teamBadgeText: { color:'#ffffff', fontSize:10, fontWeight:'bold' },
  vsContainer: { flexDirection:'row', alignItems:'center', justifyContent:'center', marginVertical:4 },
  vsLine: { flex:1, height:1, backgroundColor:'#334155' },
  vsCircle: { width:28, height:28, borderRadius:14, backgroundColor:'#f59e0b', justifyContent:'center', alignItems:'center', marginHorizontal:8 },
  vsText: { color:'#ffffff', fontWeight:'900', fontSize:11 },
  slotRow: { flexDirection:'row', justifyContent:'space-between', alignItems:'center', marginVertical:4, backgroundColor:'#0a0f1d', padding:8, borderRadius:10, borderWidth:1, borderColor:'#334155' },
  slotColorText: { fontSize:13, fontWeight:'bold', width:65 },
  slotTypeSelector: { flexDirection:'row' },
  slotTypePill: { paddingHorizontal:8, paddingVertical:5, borderRadius:6, backgroundColor:'#1e293b', marginLeft:4 },
  slotTypePillActive: { backgroundColor:'#0284c7' },
  slotTypeText: { color:'#94a3b8', fontSize:11, fontWeight:'bold' },
  slotTypeTextActive: { color:'#ffffff' },
  slotSmallBadge: { color:'#facc15', fontSize:8, fontWeight:'bold', marginTop:1 },
  missCounterBadge: { color:'#ef4444', fontSize:9, fontWeight:'900', marginTop:1 },
  checkboxRow: { flexDirection:'row', alignItems:'center', backgroundColor:'#0a0f1d', padding:10, borderRadius:12, borderWidth:1, borderColor:'#334155' },
  checkSquare: { width:22, height:22, borderRadius:6, borderWidth:2, borderColor:'#64748b', justifyContent:'center', alignItems:'center' },
  checkSquareActive: { backgroundColor:'#ef4444', borderColor:'#ef4444' },
  checkTick: { color:'#ffffff', fontWeight:'900', fontSize:13 },
  checkboxLabel: { color:'#ffffff', fontSize:12, fontWeight:'bold' },
  helperTip: { color:'#94a3b8', fontSize:10, marginTop:4 },
  inviteModalOverlay: { flex:1, backgroundColor:'rgba(0,0,0,0.85)', justifyContent:'center', alignItems:'center', padding:16 },
  invitePromptText: { color:'#ffffff', fontSize:16, textAlign:'center', marginBottom:6 },
  mainContainer: { flex:1, backgroundColor:'#0f2b5c', alignItems:'center', justifyContent:'space-between', paddingVertical:10 },
  inGameBgCover: { position:'absolute', top:0, bottom:0, left:0, right:0, width:'100%', height:'100%', opacity:0.38 },
  inGameBackdropShade: { position:'absolute', top:0, bottom:0, left:0, right:0, backgroundColor:'rgba(15,43,92,0.65)' },
  headerBar: { width:'94%', flexDirection:'row', justifyContent:'space-between', alignItems:'center', marginVertical:4, zIndex:10 },
  exitBtn: { backgroundColor:'#ef4444', paddingHorizontal:12, paddingVertical:6, borderRadius:8, borderWidth:1.5, borderColor:'#ffffff' },
  exitBtnText: { color:'#ffffff', fontWeight:'bold', fontSize:13 },
  targetGapTimerBadge: { backgroundColor:'#0f172a', paddingHorizontal:6, paddingVertical:4, borderRadius:8, borderWidth:1.5, borderColor:'#38bdf8', alignItems:'center', justifyContent:'center', marginHorizontal:4 },
  targetGapTimerText: { color:'#ffffff', fontWeight:'900', fontSize:10 },
  timerDangerPulse: { borderColor:'#ef4444', backgroundColor:'#450a0a' },
  onlineGameActions: { flexDirection:'row', alignItems:'center' },
  inGameIconBtn: { width:36, height:36, borderRadius:18, justifyContent:'center', alignItems:'center', marginHorizontal:4, borderWidth:1.5 },
  
  chatTriggerBtn: { backgroundColor:'#0284c7', borderColor:'#38bdf8', position:'relative' },
  chatBadgeDot: { position:'absolute', top:2, right:2, width:8, height:8, borderRadius:4, backgroundColor:'#facc15' },
  
  chatModalBox: { width:'92%', height:'65%', padding:12, justifyContent:'space-between' },
  chatHeaderRow: { flexDirection:'row', justifyContent:'space-between', alignItems:'center', borderBottomWidth:1, borderBottomColor:'#334155', paddingBottom:8 },
  chatTitleText: { color:'#facc15', fontWeight:'900', fontSize:15 },
  closeChatBtn: { padding:4 },
  closeChatText: { color:'#ffffff', fontSize:16, fontWeight:'bold' },
  chatListFeed: { flex:1, width:'100%' },
  chatBubbleRow: { width:'100%', marginVertical:3, flexDirection:'row' },
  chatBubbleLeft: { justifyContent:'flex-start' },
  chatBubbleRight: { justifyContent:'flex-end' },
  chatMessageBubble: { maxWidth:'78%', paddingHorizontal:10, paddingVertical:6, borderRadius:12 },
  chatBubbleMe: { backgroundColor:'#0284c7' },
  chatBubbleOpponent: { backgroundColor:'#334155' },
  chatSenderName: { fontSize:10, fontWeight:'bold', marginBottom:2 },
  chatMessageText: { color:'#ffffff', fontSize:13, fontWeight:'600' },
  chatTimeText: { color:'#cbd5e1', fontSize:8, alignSelf:'flex-end', marginTop:2 },
  noChatText: { color:'#64748b', textAlign:'center', fontSize:12, marginTop:20 },
  quickEmojiRow: { flexDirection:'row', justifyContent:'space-around', paddingVertical:6, borderTopWidth:1, borderTopColor:'#1e293b' },
  emojiCircleBtn: { padding:4, backgroundColor:'#1e293b', borderRadius:8 },
  chatInputWrap: { flexDirection:'row', alignItems:'center', marginTop:4 },
  chatTextInputField: { flex:1, backgroundColor:'#0a0f1d', borderWidth:1, borderColor:'#334155', borderRadius:10, color:'#ffffff', paddingHorizontal:12, paddingVertical:8, fontSize:13 },
  sendChatBtn: { backgroundColor:'#eab308', borderRadius:10, paddingHorizontal:12, paddingVertical:9, marginLeft:6 },
  sendChatBtnText: { color:'#000000', fontWeight:'900', fontSize:12 },
  topCardsRow: { flexDirection:'row', justifyContent:'space-between', alignItems:'center', width:BOARD_SIZE, paddingHorizontal:4, minHeight:60 },
  bottomCardsRow: { flexDirection:'row', justifyContent:'space-between', alignItems:'center', width:BOARD_SIZE, paddingHorizontal:4, minHeight:60 },
  cardContainerWrapper: { width:'46%', alignItems:'center' },
  playerCardPlaceholder: { width:'46%' },
  playerCard: { flexDirection:'column', alignItems:'center', justifyContent:'space-between', backgroundColor:'rgba(15,23,42,0.85)', paddingHorizontal:8, paddingVertical:6, borderRadius:12, borderWidth:1.5, borderColor:'#38bdf8', width:'100%' },
  activeCardGlow: { borderColor:'#facc15', backgroundColor:'rgba(30,58,138,0.9)', elevation:8, shadowColor:'#facc15', shadowOpacity:0.6, shadowRadius:10 },
  cardRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  cardNameRow: {
    width: '100%',
    alignItems: 'center',
    marginTop: 2,
    paddingHorizontal: 4,
  },
  cardPlayerName: {
    color: '#ffffff',
    fontSize: 10,
    fontWeight: 'bold',
    textAlign: 'center',
    width: '100%',
  },
  reconnectingCardDim: {
  opacity: 0.55,
  borderColor: '#f59e0b',
  backgroundColor: 'rgba(120, 53, 15, 0.7)',
},
reconnectingBadge: {
  position: 'absolute',
  top: -12,
  alignSelf: 'center',
  backgroundColor: '#f59e0b',
  paddingHorizontal: 8,
  paddingVertical: 2,
  borderRadius: 8,
  borderWidth: 1.5,
  borderColor: '#ffffff',
  zIndex: 40,
  elevation: 8,
},
reconnectingBadgeText: {
  color: '#000000',
  fontSize: 9,
  fontWeight: '900',
},
reconnectingNameText: {
  color: '#f59e0b',
  fontStyle: 'italic',
},
  cardAvatarLeft: { flexDirection:'column', alignItems:'center', width:35 },
  cardAvatarRight: { flexDirection:'column', alignItems:'center', width:35 },
  cardDiceWrap: { padding:2 },
  floatingArrowContainer: { position:'absolute', alignSelf:'center', zIndex:30 },
  arrowTopPos: { top:-24 },
  arrowIconBubble: { backgroundColor:'#f59e0b', paddingHorizontal:8, paddingVertical:2, borderRadius:6, borderWidth:1.5, borderColor:'#ffffff', elevation:6 },
  arrowIconText: { color:'#ffffff', fontWeight:'900', fontSize:14 },
  diceBox: { width:42, height:42, backgroundColor:'#ffffff', borderRadius:8, borderWidth:2, borderColor:'#cbd5e1', justifyContent:'center', alignItems:'center', padding:3 },
  diceDot: { width:6.5, height:6.5, borderRadius:3.25, backgroundColor:'#0f172a', margin:1.5 },
  diceCenter: { justifyContent:'center', alignItems:'center' },
  diceRowSpace: { flexDirection:'row', justifyContent:'space-between', width:'100%', paddingHorizontal:2 },
  diceCol: { justifyContent:'space-between' },
  pinWrapper: { alignItems:'center', width:24, height:32, justifyContent:'center' },
  pinPedestalRing: { width:24, height:24, borderRadius:12, borderWidth:2.5, backgroundColor:'rgba(255,255,255,0.95)', justifyContent:'center', alignItems:'center', elevation:5 },
  pinHeadCircle: { width:15, height:15, borderRadius:7.5, justifyContent:'center', alignItems:'center' },
  pinWhiteInnerCore: { width:8, height:8, borderRadius:4, backgroundColor:'#ffffff', justifyContent:'center', alignItems:'center' },
  pinDotCenter: { width:4, height:4, borderRadius:2 },
  stackBadgeBubble: { position:'absolute', top:-10, alignSelf:'center', backgroundColor:'#facc15', borderRadius:8, width:15, height:15, justifyContent:'center', alignItems:'center', borderWidth:1, borderColor:'#000000', zIndex:30 },
  stackBadgeText: { color:'#000000', fontSize:9, fontWeight:'900' },
  boardContainer: { width:BOARD_SIZE, height:BOARD_SIZE, backgroundColor:'#ffffff', borderWidth:2, borderColor:'#334155', borderRadius:6, overflow:'hidden', elevation:12, shadowColor:'#000', shadowOpacity:0.4, shadowRadius:8 },
  board: { width:'100%', height:'100%', position:'relative', backgroundColor:'#ffffff' },
  cell: { position:'absolute', width:CELL_SIZE, height:CELL_SIZE, borderWidth:0.6, borderColor:'#94a3b8', justifyContent:'center', alignItems:'center' },
  starCleanText: { fontSize:18, color:'#334155', fontWeight:'bold' },
  arrowCleanText: { fontSize:15, fontWeight:'900' },
  base: { position:'absolute', width:CELL_SIZE * 6, height:CELL_SIZE * 6, justifyContent:'center', alignItems:'center', padding:8 },
  redBase: { top:0, left:0, backgroundColor:'#ef4444' },
  greenBase: { top:0, right:0, backgroundColor:'#16a34a' },
  blueBase: { bottom:0, left:0, backgroundColor:'#2563eb' },
  yellowBase: { bottom:0, right:0, backgroundColor:'#eab308' },
  baseInnerWhite: { width:'80%', height:'80%', backgroundColor:'#ffffff', borderRadius:6, justifyContent:'space-around', padding:8, borderWidth:1, borderColor:'#cbd5e1' },
  basePocketAbsolute: {
    position: 'absolute',
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.5)',
    elevation: 3,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  playerLabel: { position:'absolute', fontSize:11, fontWeight:'900', color:'#ffffff', textShadowColor:'rgba(0,0,0,0.8)', textShadowRadius:3 },
  playerLabelBottom: {
    bottom: 4,
    left: 0,
    right: 0,
    textAlign: 'center',
  },
  playerLabelTop: {
    top: 4,
    left: 0,
    right: 0,
    textAlign: 'center',
  },
  playerLabelRight: {
    right: 4,
    top: '50%',
    width: '92%',
    textAlign: 'center',
  },
  centerHome: { position:'absolute', top:CELL_SIZE * 6, left:CELL_SIZE * 6, width:CELL_SIZE * 3, height:CELL_SIZE * 3, overflow:'hidden' },
  centerTriangleTop: { position:'absolute', top:0, left:0, width:0, height:0, borderLeftWidth:(CELL_SIZE * 3) / 2, borderRightWidth:(CELL_SIZE * 3) / 2, borderTopWidth:(CELL_SIZE * 3) / 2, borderLeftColor:'transparent', borderRightColor:'transparent', borderTopColor:'#16a34a' },
  centerTriangleRight: { position:'absolute', top:0, right:0, width:0, height:0, borderTopWidth:(CELL_SIZE * 3) / 2, borderBottomWidth:(CELL_SIZE * 3) / 2, borderRightWidth:(CELL_SIZE * 3) / 2, borderTopColor:'transparent', borderBottomColor:'transparent', borderRightColor:'#eab308' },
  centerTriangleBottom: { position:'absolute', bottom:0, left:0, width:0, height:0, borderLeftWidth:(CELL_SIZE * 3) / 2, borderRightWidth:(CELL_SIZE * 3) / 2, borderBottomWidth:(CELL_SIZE * 3) / 2, borderLeftColor:'transparent', borderRightColor:'transparent', borderBottomColor:'#2563eb' },
  centerTriangleLeft: { position:'absolute', top:0, left:0, width:0, height:0, borderTopWidth:(CELL_SIZE * 3) / 2, borderBottomWidth:(CELL_SIZE * 3) / 2, borderLeftWidth:(CELL_SIZE * 3) / 2, borderTopColor:'transparent', borderBottomColor:'transparent', borderLeftColor:'#ef4444' },
  tokenWrapper: { position:'absolute', width:CELL_SIZE, height:CELL_SIZE, justifyContent:'center', alignItems:'center' },
});
